config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'    
  resources :logs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @log1 = 5
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:syohai, :roll, :survive, :memo)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2017 k.kimura
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Jinro-bo", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>人狼簿</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_for(log) do |f| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :勝敗 %>
    <%= select :log, :syohai, [
    ["勝ち", "勝ち"], 
    ["負け", "負け"],
    ["引き分け", "引き分け"]
    ] %>
  </div>

  <div class="field">
    <%= f.label :役職 %>
    <%= select :log, :roll, 
    [
      ["村人", "村人"],
      ["預言者(占い師)", "預言者(占い師)"],
      ["霊媒師（霊能者）", "霊媒師（霊能者）"],
      ["狩人（ボデイーガード）", "狩人（ボデイーガード）"],
      ["狼", "狼"],
      ["狂人", "狂人"],
      ["狐", "狐"],
      ["ハンター", "ハンター"],
      ["恋人", "恋人"],
      ["その他村側役職","その他村側役職"],
      ["その他狼側役職","その他狼側役職"],
      ["その他第三陣営","その他第三陣営"]
    ] 
    %>
  </div>

  <div class="field">
    <%= f.label :ゲーム終了時の生死 %>
    <%= select :log, :survive, 
    [
      ["生存", "生存"],
      ["死亡（吊られ）", "死亡（吊られ）"],
      ["死亡（噛まれ）", "死亡（噛まれ）"],
      ["死亡（その他）", "死亡（その他）"]
    ] 
    %>
  </div>

  <div class="field">
    <%= f.label :memo %>
    <%= f.text_area :memo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記録</h1>

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://naver.github.io/billboard.js/release/latest/dist/billboard.js"></script>
<link rel="stylesheet" href="https://naver.github.io/billboard.js/release/latest/dist/billboard.css">
<h2>データチャート（データは仮です）</h2>
<div class="charts">
  <div id="chart-syohai"></div>
  <div id="chart-roll"></div>
  <div id="chart-survive"></div>
</div>

<table>
  <thead>
    <tr>
      <th>勝敗</th>
      <th>役職</th>
      <th>ゲーム終了時の生死</th>
      <th>メモ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.syohai %></td>
        <td><%= log.roll %></td>
        <td><%= log.survive %></td>
        <td><%= log.memo %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

<script>
bb.generate({
  bindto: "#chart-syohai",
  "data": {
    "columns": [
      [
        "勝ち",
        <%= @log1 %>
      ],
      [
        "負け",
        3
      ],
      [
        "引き分け",
        1
      ]
    ],
    "type": "pie"
  },
  "pie": {
    "label": {
      "format": function (value, ratio, id) {
		return d3.format('')(value);
	}
    }
  }
});
bb.generate({
  bindto: "#chart-roll",
  "data": {
    "columns": [
      [
        "村人",
        <%= @log1 %>
      ],
      [
        "預言者",
        3
      ],
      [
        "人外",
        5
      ]
    ],
    "type": "pie"
  },
  "pie": {
    "label": {
      "format": function (value, ratio, id) {
		return d3.format('')(value);
	}
    }
  }
});
bb.generate({
  bindto: "#chart-survive",
  "data": {
    "columns": [
      [
        "生存",
        <%= @log1 %>
      ],
      [
        "死亡（噛まれ）",
        3
      ],
      [
        "死亡（吊られ）",
        1
      ]
    ],
    "type": "pie"
  },
  "pie": {
    "label": {
      "format": function (value, ratio, id) {
		return d3.format('')(value);
	}
    }
  }
});
</script>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Syohai:</strong>
  <%= @log.syohai %>
</p>

<p>
  <strong>Roll:</strong>
  <%= @log.roll %>
</p>

<p>
  <strong>Survive:</strong>
  <%= @log.survive %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @log.memo %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>

app/views/static_pages/home.html.erb
<h1>はじめに</h1>
<p>このアプリは人狼ゲームの家計簿です。<br>言い換えると、人狼ゲームの戦歴を記録するアプリです。</p>

<h2>人狼ゲームとは？</h2>
<blockquote>
  プレイヤーはそれぞれが村人と村人に化けた人狼となり、自分自身の正体がばれないようにしながら他のプレイヤーと交渉して相手の正体を探る。ゲームは半日単位で進行し、昼には全プレイヤーの投票により決まった人狼容疑者1名の処刑が、夜には人狼による村人の襲撃が行われる。全ての人狼を処刑することができれば村人チームの勝ち、生き残った人狼と同数まで村人を減らすことができれば人狼チームの勝ちとなる。
</blockquote>
<iframe width="853" height="480" src="https://www.youtube.com/embed/2D-ebbjIh1Q" frameborder="0" allowfullscreen></iframe>

<br><br><br>
<%= link_to '記録する', logs_path %>